apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
stringData:
  mongodb-username: admin
  mongodb-password: NewStrongPass456!
  mongodb-host: 10.32.10.207
  mongodb-database: secure-app 