apiVersion: v1
kind: Service
metadata:
  name: secure-nodejs-service
  labels:
    app: secure-nodejs-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: secure-nodejs-app